# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crp6enbkj885jd9uglda/stg_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2023-05-02-r1"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-65fqhuubchc2v4nm.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_concumer"
  KAFKA_CONSUMER_PASSWORD: "lcalca34966"
  KAFKA_CONSUMER_GROUP: "main-consumer-group"
  KAFKA_SOURCE_TOPIC: "order-service-orders"
  KAFKA_DESTINATION_TOPIC: "stg-service-orders"

  PG_WAREHOUSE_HOST: "rc1b-wa3qczuimfwszsrf.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "de_db_user"
  PG_WAREHOUSE_PASSWORD: "dedbuser"


  REDIS_HOST: "c-c9qbsagnnhi4mtfjdort.rw.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "lcalca34966"

  BATCH_SIZE: "10"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
